# TODO: 'schedules' will need to be updated to coincide with the meeting frequency

name: Create TSC meeting agenda from items tagged meeting-agenda
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-07-30T09:00:00.0Z/P1D
        createWithin: P1D
        issueTitle: "TSC Meeting <%= date.toFormat('yyyy-MM-dd') %>"
        agendaLabel: meeting-agenda
